import { PrankConfig } from '../types/prank';

export interface PrankTemplate {
  id: string;
  name: string;
  description: string;
  icon: string; // Emoji representing the template
  config: PrankConfig;
}

export const PRANK_TEMPLATES: PrankTemplate[] = [
  {
    id: 'fbi-seizure',
    name: 'Alerta Policial / FBI',
    description: 'Orden de bloqueo cibernético con sirena de emergencia, IP y temporizador.',
    icon: '🚨',
    config: {
      prankType: 'fbi-warning',
      title: '¡DISPOSITIVO BLOQUEADO POR LA POLICÍA NACIONAL!',
      message: 'Se ha detectado actividad sospechosa y tráfico de archivos no autorizados.',
      intensity: 8,
      duration: 15,
      theme: 'fbi-red',
      fullscreen: true,
      revealText: '¡Tranqui! Tu dispositivo está 100% libre de multas 🚔😂',
      targetName: '',
      showReveal: true,
      appTheme: 'dark',
      visualIntensity: 'high',
      accentColor: '#ef4444',
      soundEnabled: true,
      vibrationEnabled: true,
      escapeMode: 'stealth',
      linkDisguise: 'pdf-doc',
    },
  },
  {
    id: 'battery-explosion',
    name: 'Batería 98°C Overheat',
    description: 'Peligro de sobrecalentamiento crítico con medidor térmico y vibración.',
    icon: '🔥',
    config: {
      prankType: 'battery-explosion',
      title: '¡SOBRECALENTAMIENTO EXTREMO!',
      message: 'La temperatura interna del procesador ha alcanzado 98°C. Apague el equipo.',
      intensity: 9,
      duration: 12,
      theme: 'thermal-red',
      fullscreen: true,
      revealText: '¡Tu batería está fría y saludable! Puro susto ❄️📱',
      targetName: '',
      showReveal: true,
      appTheme: 'dark',
      visualIntensity: 'high',
      accentColor: '#dc2626',
      soundEnabled: true,
      vibrationEnabled: true,
      escapeMode: 'stealth',
      linkDisguise: 'giveaway',
    },
  },
  {
    id: 'broken-glass',
    name: 'Pantalla Rota / Cristal',
    description: 'Simulador interactivo de fisura de cristal con sonido de crujido y tacto.',
    icon: '🔨',
    config: {
      prankType: 'broken-glass',
      title: '⚠️ PANTALLA DAÑADA',
      message: 'Fisura física detectada en el panel táctil.',
      intensity: 7,
      duration: 10,
      theme: 'glass-crack',
      fullscreen: true,
      revealText: '¡Tu pantalla no tiene un solo rasguño! ✨📱',
      targetName: '',
      showReveal: true,
      appTheme: 'dark',
      visualIntensity: 'medium',
      accentColor: '#ffffff',
      soundEnabled: true,
      vibrationEnabled: true,
      escapeMode: 'stealth',
      linkDisguise: 'none',
    },
  },
  {
    id: 'whatsapp-hacked',
    name: 'WhatsApp Clonado',
    description: 'Aviso de sesión duplicada en Brasil y exportación de mensajes.',
    icon: '💬',
    config: {
      prankType: 'whatsapp-hacked',
      title: '¡NUEVO DISPOSITIVO VINCULADO!',
      message: 'Se ha iniciado sesión desde una IP desconocida en San Pablo, Brasil.',
      intensity: 8,
      duration: 15,
      theme: 'whatsapp-green',
      fullscreen: true,
      revealText: '¡Tus chats están 100% seguros y privados! 💬🔐',
      targetName: '',
      showReveal: true,
      appTheme: 'dark',
      visualIntensity: 'medium',
      accentColor: '#00a884',
      soundEnabled: true,
      vibrationEnabled: true,
      escapeMode: 'stealth',
      linkDisguise: 'whatsapp-backup',
    },
  },
  {
    id: 'win11-update',
    name: 'Actualización Windows 11',
    description: 'Simula una actualización eterna de Windows 11 con porcentaje cambiante.',
    icon: '💻',
    config: {
      prankType: 'fake-update',
      title: 'Instalando actualizaciones del sistema',
      message: 'No apagues el equipo. Esto podría tardar unos minutos.',
      intensity: 5,
      duration: 15,
      theme: 'windows-11',
      fullscreen: true,
      revealText: '¡Tu sistema está al día! ... Mentira, es una broma 😜',
      targetName: '',
      showReveal: true,
      appTheme: 'dark',
      visualIntensity: 'medium',
      accentColor: '#8b5cf6',
      soundEnabled: false,
      vibrationEnabled: false,
      escapeMode: 'stealth',
      linkDisguise: 'none',
    },
  },
  {
    id: 'bsod',
    name: 'Pantalla Azul (BSOD)',
    description: 'La clásica pantalla azul de la muerte de Windows con código QR.',
    icon: '🔵',
    config: {
      prankType: 'fake-error',
      title: 'CRITICAL_PROCESS_DIED',
      message: 'Se ha producido un problema en su dispositivo y necesita reiniciarse.',
      intensity: 6,
      duration: 12,
      theme: 'bsod',
      fullscreen: true,
      revealText: '¡Tu computadora está sana y salva! 😂',
      targetName: '',
      showReveal: true,
      appTheme: 'dark',
      visualIntensity: 'medium',
      accentColor: '#06b6d4',
      soundEnabled: true,
      vibrationEnabled: true,
      escapeMode: 'stealth',
      linkDisguise: 'none',
    },
  },
  {
    id: 'matrix-glitch',
    name: 'Invasión Hacker',
    description: 'Filtros de distorsión, terminal Cyberpunk y cursor loco.',
    icon: '⚡',
    config: {
      prankType: 'glitch',
      title: 'ALERTA DE SEGURIDAD: INTRUSIÓN',
      message: 'Infiltrando cortafuegos principales... Descargando memoria caché.',
      intensity: 7,
      duration: 10,
      theme: 'cyberpunk',
      fullscreen: true,
      revealText: '¡Hackeado! Jaja, broma inofensiva 🤖',
      targetName: '',
      showReveal: true,
      appTheme: 'neon',
      visualIntensity: 'high',
      accentColor: '#ec4899',
      soundEnabled: true,
      vibrationEnabled: true,
      escapeMode: 'stealth',
      linkDisguise: 'none',
    },
  },
  {
    id: 'free-ram',
    name: 'Descargar RAM Gratis',
    description: 'Barra de carga infinita con mensajes de optimización absurdos.',
    icon: '🐏',
    config: {
      prankType: 'loading',
      title: 'Descargando 64GB DDR5 RAM Gratis',
      message: 'Asignando transistores en la nube molecular...',
      intensity: 5,
      duration: 12,
      theme: 'downloading-ram',
      fullscreen: true,
      revealText: '¡Disfruta tu nueva memoria RAM mental! 🧠🐏',
      targetName: '',
      showReveal: true,
      appTheme: 'retro',
      visualIntensity: 'medium',
      accentColor: '#f59e0b',
      soundEnabled: false,
      vibrationEnabled: false,
      escapeMode: 'stealth',
      linkDisguise: 'bank-transfer',
    },
  },
];
export type { PrankConfig };
